package mud.events;

/*
 * Copyright (c) 2013 Jeremy N. Harton
 * Released under the MIT License:
 * LICENSE.txt, http://opensource.org/licenses/MIT
 */

import java.util.EventObject;
import mud.objects.Room;

/**
 * An event generated by the room in which something was said
 * 
 * @author Jeremy
 *
 */
@SuppressWarnings("serial")
public class SayEvent extends EventObject {
	private String message;
	
	public SayEvent(final Room source, final String message) {
		super(source);
		this.message = message;
	}
	
	@Override
	public Room getSource() {
		return (Room) source;
	}
	
	public String getMessage() {
		return this.message;
	}
}